apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.clientService.name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ports:
    - name: client
      port: {{ .Values.clientService.externalPort }}
      targetPort: {{ .Values.clientService.internalPort }}
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serverService.name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ports:
    - name: client
      protocol: TCP
      port: {{ .Values.serverService.clientPort.externalPort }}
      targetPort: {{ .Values.serverService.clientPort.internalPort }}
    - name: server
      protocol: TCP
      port: {{ .Values.serverService.serverPort.externalPort }}
      targetPort: {{ .Values.serverService.serverPort.internalPort }}
  selector:
    app: {{ .Chart.Name }}
