apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
rules:
  - apiGroups:
      - {{ .Values.APIGroup }}
    resources:
      - trainingjobs
      - trainingjobs/status
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
      - nodes
    verbs:
      - "list"
