{{- $auth := (printf "%s:%s" .Values.jfrog.username .Values.jfrog.password) | b64enc -}}
{{- $config := (printf `{"auths":{"breezeml.jfrog.io":{"auth":"%s"}}}` $auth) | b64enc -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.jfrog.secretName }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $config }}
