apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.jfrog.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ .Values.jfrog.username }}
  password: {{ .Values.jfrog.password }}
