apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}-worker-role
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
rules:
- apiGroups:
    - {{ .Values.group }}
  resources:
    - "trainingjobs"
    - "trainingjobs/status"
  verbs:
    - "get"
- apiGroups:
    - ""
  resources:
    - "pods"
  verbs:
    - "get"
