apiVersion: batch/v1
kind: Job
metadata:
  name: sleep-job
spec:
  template:
    spec:
      containers:
        - name: busybox
          image: busybox
          args:
            - sleep
            - "200"
      restartPolicy: OnFailure